version: '3'

services:
  wedding_purple_clouds_php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-dev
    volumes:
      - .:/var/www/html
    networks: ["purple_clouds_network_internal"]

  wedding_purple_clouds_nginx:
    image: nginx:latest
    ports:
      - "8003:8003"
    depends_on:
      - wedding_purple_clouds_php
    links:
      - wedding_purple_clouds_php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_internal"]

  wedding_purple_clouds_assets:
    image: nginx:latest
    ports:
      - "8901:8901"
    volumes:
      - ./public/assets:/static/assets
      - ./docker/assets/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_internal"]

networks:
  purple_clouds_network_internal: {"external": {"name": "purple_clouds_network_internal"}}
